# Site settings
title: "Opgelicht Overijssel"
description: "Een onderzoeksplatform naar Digitale Oplichting in Overijsel"
url: "opgelichtoverijssel.nl"
author:
  name: "Redactie"
  email: "info@opgelichtoverijssel.nl"
  url: "opgelichtoverijssel.nl"

# Build settings
baseurl: opgelichtoverijssel.nl/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: true
reverse: true

theme: jekyll-theme-cayman
