# Site settings
title: "Opgelicht in Overijssel"
description: "Onderzoek naar digitale oplichting in Overijssel"
url: "https://opgelichtoverijssel.nl"
author:
  name: "Redactie Opgelicht Overijssel"
  email: "info@opgelichtoverijssel.nl"
  url: "https://opgelichtoverijssel.nl"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate

# Custom variables
version: "1.1.0"

# Options
custom_header: true
custom_nav_footer: false
reverse: false

theme: jekyll-theme-cayman
